debian_nfs_server/nfs-kernel-server_1.2.8-6ubuntu1.2_amd64.deb:
  size: 85826
  object_id: cc6a7832-d310-46de-4e72-7684bd1790ba
  sha: 1ef96876212fb4ce6e3ebb3e18d9ec2d2d9ceb48
gitlab-ee-omnibus/trusty/gitlab-ee_10.8.7-ee.0_amd64.deb:
  size: 478214494
  object_id: ea430ab2-e28b-4e25-56fc-e07e619ec8fc
  sha: e21ffbde20283f9fb63816b0eefd2cf7a26c0731
gitlab-ee-omnibus/xenial/gitlab-ee_10.8.7-ee.0_amd64.deb:
  size: 479984780
  object_id: 7ec690c8-f206-4fa8-7d6f-2a7100132703
  sha: 011063e55ecd0d8e5ac0e0c86d0731f47b787b12
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: a3aaf9bc-dc49-46e5-5c03-3508f63fd00b
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 1f28d84a-8753-4dbd-7eef-d09401b07e3c
  sha: 57d69f44f3e058e48a7b79595d36076eb21f5942
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 2af5c6ab-e7db-40c6-5e6e-649723676a86
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1%3a1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 85a5797f-da9a-426e-504b-14bbc2fc60c5
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/nfs-kernel-server_1.2.8-9ubuntu12.1_amd64.deb:
  size: 87964
  object_id: 61b6d281-c85e-4a76-7411-61a575a5406c
  sha: 6a6a863c759ec3b9417d6b0a56ab29dc690bcfda
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 3cde3aeb-72f3-47b2-6781-120e235bda9d
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
