---
debian_nfs_server/nfs-kernel-server_1.2.5-3ubuntu3_amd64.deb:
  object_id: 6bbb5b7a-4501-4afa-9a70-7e6dd2c92be2
  sha: 65457bbeda336dc4b710cd68f71e9dd218fdf594
  size: 124348
go/go1.4.1.linux-amd64.tar.gz:
  object_id: fcf24fb5-3d51-4f13-9973-e8e195d71dbf
  sha: 3e871200e13c0b059b14866d428910de0a4c51ed
  size: 62402109
gitlab-ee-omnibus/gitlab-ee_8.16.7-ee.0_amd64.deb:
  object_id: 63d13c9f-9a4a-4516-9b1f-4bc785c57422
  sha: 1def75cf77327a329e3a4cc275de84af768d0712
  size: 283975416
